import { useMemo, useRef, useState, type ReactNode } from 'react';
import {
	useFrappeDeleteDoc,
	useFrappeFileUpload,
	useFrappeGetCall,
	useFrappePostCall,
} from 'frappe-react-sdk';
import { Link } from 'react-router-dom';
import { Icon } from '@/components/Icon';
import { Field, SearchSelect, SelectInput, TextArea, TextInput } from '@/components/form';
import { Card, CHead, EmptyMsg, Modal, Tag } from '@/components/ui';
import {
	API,
	DOC_STATUSES,
	docCkTone,
	docIsBlockingNow,
	docIsDone,
	isGeneratableDoc,
	parseServerError,
	type DocInstanceRow,
	type DocStatus,
	type DocTypeOption,
	type ShipmentDocumentsData,
} from '@/lib/api';
import { daysUntil, fmtDate } from '@/lib/format';

export const RESPONSIBLE_PARTIES = [
	'Us',
	'CHA',
	'Supplier',
	'Shipping Line/Airline',
	'Bank',
	'Authority',
	'Customer',
];

/** Mockup grouping: Logistics & banking share a band; Company rarely shows. */
const GROUPS: { label: string; categories: string[] }[] = [
	{ label: 'Commercial · generated by ExportFlow', categories: ['Commercial'] },
	{ label: 'Regulatory · with authorities', categories: ['Regulatory'] },
	{ label: 'Quality · from supplier', categories: ['Quality'] },
	{ label: 'Logistics & banking', categories: ['Logistics', 'Banking'] },
	{ label: 'Company', categories: ['Company'] },
];

function CkIcon({ doc }: { doc: DocInstanceRow }) {
	const tone = docCkTone(doc);
	if (tone === 'none') return <span className="ck none" />;
	return (
		<span className={`ck ${tone}`}>
			{tone === 'ok' ? (
				<Icon name="check" size={11} strokeWidth={3} />
			) : tone === 'err' ? (
				<Icon name="exclamation" size={11} strokeWidth={3} />
			) : (
				<Icon name="clock" size={11} strokeWidth={2.6} />
			)}
		</span>
	);
}

/** Second line of a checklist row: number · date · state, blocking warning. */
function rowDetail(doc: DocInstanceRow): ReactNode {
	const bits: ReactNode[] = [];
	if (doc.document_number) bits.push(<span className="data" key="no">{doc.document_number}</span>);
	if (doc.document_date) bits.push(<span key="dt">{fmtDate(doc.document_date)}</span>);
	if (doc.originals) bits.push(<span key="oc">{doc.originals} originals{doc.copies ? ` + ${doc.copies} copies` : ''}</span>);
	bits.push(<span key="st">{doc.status === 'Pending' ? 'pending' : doc.status.toLowerCase()}</span>);
	if (doc.blocking && doc.blocked_milestone && docCkTone(doc) === 'err') {
		bits.push(
			<span key="blk" style={{ color: 'var(--err)', fontWeight: 500 }}>
				blocking {doc.blocked_milestone}
			</span>,
		);
	}
	const dueDays = doc.due_date && !docIsDone(doc) ? daysUntil(doc.due_date) : null;
	if (dueDays !== null) {
		bits.push(
			<span
				key="due"
				style={dueDays <= 7 ? { color: 'var(--err)', fontWeight: 500 } : undefined}
			>
				due {fmtDate(doc.due_date)}
			</span>,
		);
	}
	return bits.flatMap((b, i) => (i === 0 ? [b] : [' · ', b]));
}

export function DocumentChecklist({ shipment }: { shipment: string }) {
	const { data, error, isLoading, mutate } = useFrappeGetCall<{ message: ShipmentDocumentsData }>(
		API.shipmentDocuments,
		{ shipment },
	);
	const [open, setOpen] = useState<DocInstanceRow | null>(null);
	const [adding, setAdding] = useState(false);
	const { call: generate } = useFrappePostCall<{
		message: { file_url: string; status: DocStatus; document_number: string | null };
	}>(API.generateDocument);
	const { call: generateAll } = useFrappePostCall<{
		message: {
			results: { name: string; document_type: string; ok: boolean; error?: string }[];
			generated: number;
			failed: number;
		};
	}>(API.generateAllDocuments);
	const [genName, setGenName] = useState<string | null>(null);
	const [genErr, setGenErr] = useState<{ name: string; msg: string } | null>(null);
	const [bulkBusy, setBulkBusy] = useState(false);
	const [bulkMsg, setBulkMsg] = useState<{ tone: 'ok' | 'err'; text: string } | null>(null);

	const docs = data?.message.documents ?? [];
	const types = data?.message.document_types ?? [];
	const done = docs.filter(docIsDone).length;
	// origin + print format decide whether ExportFlow can produce the PDF itself
	const typeMap = new Map(types.map((t) => [t.name, t] as [string, DocTypeOption]));
	// rows the "Generate all" pass would actually produce (Pending + generatable)
	const pendingGeneratable = docs.filter(
		(d) => d.status === 'Pending' && isGeneratableDoc(typeMap.get(d.document_type)),
	).length;

	async function onGenerateRow(d: DocInstanceRow) {
		setGenErr(null);
		setBulkMsg(null); // a per-row action supersedes the stale bulk banner
		setGenName(d.name);
		try {
			await generate({ name: d.name });
			await mutate();
		} catch (e) {
			setGenErr({ name: d.name, msg: parseServerError(e) });
		} finally {
			setGenName(null);
		}
	}

	async function onGenerateAll() {
		setGenErr(null);
		setBulkMsg(null);
		setBulkBusy(true);
		try {
			const res = await generateAll({ shipment });
			const { results, generated, failed } = res.message;
			await mutate();
			if (failed > 0) {
				const failedTypes = Array.from(new Set(results.filter((r) => !r.ok).map((r) => r.document_type)));
				const shown = failedTypes.slice(0, 2).join(', ') + (failedTypes.length > 2 ? '…' : '');
				setBulkMsg({ tone: 'err', text: `Generated ${generated}, ${failed} failed: ${shown}` });
			} else if (generated === 0) {
				setBulkMsg({ tone: 'ok', text: 'Nothing to generate' });
			} else {
				setBulkMsg({ tone: 'ok', text: `Generated ${generated} document${generated === 1 ? '' : 's'}` });
			}
		} catch (e) {
			setBulkMsg({ tone: 'err', text: parseServerError(e) });
		} finally {
			setBulkBusy(false);
		}
	}

	function openDoc(d: DocInstanceRow) {
		setGenErr(null);
		setOpen(d);
	}

	const grouped = useMemo(
		() =>
			GROUPS.map((g) => ({
				...g,
				rows: docs.filter((d) => g.categories.includes(d.category ?? '')),
			})).filter((g) => g.rows.length > 0),
		[docs],
	);

	return (
		<Card>
			<CHead
				icon="file-text"
				title="Document checklist"
				count={docs.length ? `${done} / ${docs.length}` : undefined}
				bar={docs.length ? (done / docs.length) * 100 : undefined}
				action={
					<span style={{ display: 'flex', gap: 14, alignItems: 'center' }}>
						{bulkMsg && (
							<span className={bulkMsg.tone === 'err' ? 'ferr' : 'fhint'} style={{ fontSize: 12 }}>
								{bulkMsg.text}
							</span>
						)}
						{pendingGeneratable > 0 && (
							<a
								href="#"
								onClick={(e) => {
									e.preventDefault();
									if (!bulkBusy) void onGenerateAll();
								}}
							>
								{bulkBusy ? 'Generating…' : 'Generate all'}
							</a>
						)}
						<a
							href="#"
							onClick={(e) => {
								e.preventDefault();
								setAdding(true);
							}}
						>
							Add document
						</a>
						<Link
							to={`/documents?shipment=${encodeURIComponent(shipment)}`}
							style={{ fontSize: '12.5px', color: 'var(--iris)', textDecoration: 'none', fontWeight: 500 }}
						>
							Open all
						</Link>
					</span>
				}
			/>
			{isLoading ? (
				<div className="sub" style={{ padding: '16px 18px' }}>
					Loading…
				</div>
			) : error ? (
				<div className="ferr" style={{ padding: '14px 18px' }}>{parseServerError(error)}</div>
			) : docs.length === 0 ? (
				<EmptyMsg
					title="No documents required yet"
					text="The checklist builds itself from the shipment's mode, incoterm, LC and purchase orders."
				/>
			) : (
				<div className="docrows">
					{grouped.map((g) => (
						<div key={g.label}>
							<div className="docgrp">{g.label}</div>
							{g.rows.map((d) => {
								const canGen = isGeneratableDoc(typeMap.get(d.document_type));
								return (
									<div
										className="drow"
										key={d.name}
										style={{ cursor: 'pointer' }}
										role="button"
										tabIndex={0}
										onClick={() => openDoc(d)}
										onKeyDown={(e) => {
											if (e.key === 'Enter' || e.key === ' ') {
												e.preventDefault();
												openDoc(d);
											}
										}}
									>
										<CkIcon doc={d} />
										<div className="nm">
											<div className="t1">{d.document_type}</div>
											<div className="t2">
												{rowDetail(d)}
												{genErr?.name === d.name && (
													<span style={{ color: 'var(--err)', fontWeight: 500 }}>
														{' · '}
														{genErr.msg}
													</span>
												)}
											</div>
										</div>
										<span className="who">{d.responsible_party ?? '—'}</span>
										<span
											className="dacts"
											onClick={(e) => e.stopPropagation()}
											onKeyDown={(e) => e.stopPropagation()}
										>
											{d.file && (
												<a className="act" href={d.file} target="_blank" rel="noreferrer">
													View PDF
												</a>
											)}
											{canGen ? (
												<button
													type="button"
													className="act"
													disabled={genName === d.name}
													onClick={() => void onGenerateRow(d)}
												>
													{genName === d.name
														? 'Generating…'
														: d.file
															? 'Regenerate'
															: 'Generate PDF'}
												</button>
											) : (
												!d.file && (
													<a
														className="act"
														href="#"
														onClick={(e) => {
															e.preventDefault();
															openDoc(d);
														}}
													>
														Update
													</a>
												)
											)}
										</span>
									</div>
								);
							})}
						</div>
					))}
				</div>
			)}
			{open && (
				<DocumentModal
					doc={open}
					types={types}
					onClose={() => setOpen(null)}
					onSaved={() => {
						setOpen(null);
						mutate();
					}}
					onChanged={() => void mutate()}
				/>
			)}
			{adding && (
				<AddDocumentModal
					shipment={shipment}
					types={types}
					onClose={() => setAdding(false)}
					onSaved={() => {
						setAdding(false);
						mutate();
					}}
				/>
			)}
		</Card>
	);
}

/** Edit a Document Instance: status, identifiers, file, generation.
 *  `onChanged` refreshes the list behind the modal without closing it. */
export function DocumentModal({
	doc,
	types,
	onClose,
	onSaved,
	onChanged,
}: {
	doc: DocInstanceRow;
	types: DocTypeOption[];
	onClose: () => void;
	onSaved: () => void;
	onChanged?: () => void;
}) {
	const type = types.find((t) => t.name === doc.document_type);
	const canGenerate = isGeneratableDoc(type);
	// LC presentation / GST deadlines stamp this automatically on engine rows
	const dueLocked = doc.source !== 'Manual';

	const [form, setForm] = useState({
		status: doc.status as DocStatus,
		document_number: doc.document_number ?? '',
		document_date: doc.document_date ?? '',
		due_date: doc.due_date ?? '',
		responsible_party: doc.responsible_party ?? '',
		remarks: doc.remarks ?? '',
	});
	const [err, setErr] = useState<string | null>(null);
	const [fileUrl, setFileUrl] = useState<string | null>(doc.file);
	const fileInput = useRef<HTMLInputElement | null>(null);

	const { call: update, loading: saving } = useFrappePostCall(API.updateDocInstance);
	const { call: attachFile, loading: attaching } = useFrappePostCall(API.attachDocFile);
	const { call: generate, loading: generating } = useFrappePostCall<{
		message: { file_url: string; status: DocStatus; document_number: string | null };
	}>(API.generateDocument);
	const { upload, loading: uploading } = useFrappeFileUpload();
	const { deleteDoc, loading: deleting } = useFrappeDeleteDoc();

	const set = <K extends keyof typeof form>(key: K, value: (typeof form)[K]) =>
		setForm((f) => ({ ...f, [key]: value }));

	function formValues(): Record<string, string> {
		if (!dueLocked) return { ...form };
		// engine rows own their due date — never send it back
		const values: Record<string, string> = { ...form };
		delete values.due_date;
		return values;
	}

	async function onSave() {
		setErr(null);
		try {
			await update({ name: doc.name, values: formValues() });
			onSaved();
		} catch (e) {
			setErr(parseServerError(e));
		}
	}

	async function onGenerate() {
		setErr(null);
		try {
			// persist edits first so the PDF carries them
			await update({ name: doc.name, values: formValues() });
			const result = await generate({ name: doc.name });
			setFileUrl(result.message.file_url);
			onSaved();
		} catch (e) {
			setErr(parseServerError(e));
		}
	}

	async function onUpload(file: File) {
		setErr(null);
		try {
			// persist edits first so the upload never costs the user their form
			await update({ name: doc.name, values: formValues() });
			const res = await upload(file, {
				doctype: 'Document Instance',
				docname: doc.name,
				fieldname: 'file',
				isPrivate: true,
			});
			// frappe's upload never writes the Attach field itself
			await attachFile({ name: doc.name, file_url: res.file_url });
			setFileUrl(res.file_url);
			onChanged?.();
		} catch (e) {
			setErr(parseServerError(e));
		}
	}

	async function onDelete() {
		setErr(null);
		try {
			await deleteDoc('Document Instance', doc.name);
			onSaved();
		} catch (e) {
			setErr(parseServerError(e));
		}
	}

	const busy = saving || generating || uploading || attaching || deleting;

	return (
		<Modal title={doc.document_type} icon="file-text" onClose={onClose}>
			<div style={{ padding: '12px 18px 0', display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
				<Tag tone={docIsDone(doc) ? 'ok' : 'pend'}>{doc.status}</Tag>
				{doc.blocking === 1 && doc.blocked_milestone && (
					<Tag tone={docIsBlockingNow(doc) ? 'err' : 'ok'}>
						{docIsBlockingNow(doc) ? 'blocks' : 'cleared for'} {doc.blocked_milestone}
					</Tag>
				)}
				{doc.source !== 'Manual' && (
					<span className="fhint">Required by {doc.source === 'LC' ? 'the letter of credit' : 'checklist rules'}</span>
				)}
			</div>
			{doc.description && (
				<div className="fhint" style={{ padding: '8px 18px 0' }}>
					{doc.description}
				</div>
			)}
			<div className="formgrid">
				<Field label="Status">
					<SelectInput
						value={form.status}
						onChange={(v) => set('status', v as DocStatus)}
						options={DOC_STATUSES.map((s) => ({ value: s }))}
					/>
				</Field>
				<Field label="Responsible">
					<SelectInput
						value={form.responsible_party}
						onChange={(v) => set('responsible_party', v)}
						options={RESPONSIBLE_PARTIES.map((p) => ({ value: p }))}
						allowEmpty
					/>
				</Field>
				<Field label="Document number">
					<TextInput mono value={form.document_number} onChange={(v) => set('document_number', v)} />
				</Field>
				<Field label="Document date">
					<TextInput type="date" value={form.document_date} onChange={(v) => set('document_date', v)} />
				</Field>
				<Field
					label="Due date"
					hint={dueLocked ? 'Tracked automatically from LC / GST deadlines' : undefined}
				>
					<TextInput
						type="date"
						value={form.due_date}
						disabled={dueLocked}
						onChange={(v) => set('due_date', v)}
					/>
				</Field>
				<Field label="File">
					<div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
						{fileUrl ? (
							<a className="act" href={fileUrl} target="_blank" rel="noreferrer" style={{ fontSize: 13, color: 'var(--iris)' }}>
								View attached
							</a>
						) : (
							<span className="fhint">none yet</span>
						)}
						<button
							type="button"
							className="btn"
							style={{ padding: '5px 12px' }}
							disabled={busy}
							onClick={() => fileInput.current?.click()}
						>
							{uploading ? 'Uploading…' : 'Upload'}
						</button>
						<input
							ref={fileInput}
							type="file"
							style={{ display: 'none' }}
							onChange={(e) => {
								const f = e.target.files?.[0];
								if (f) void onUpload(f);
								e.target.value = '';
							}}
						/>
					</div>
				</Field>
				<div className="span2">
					<Field label="Remarks">
						<TextArea value={form.remarks} onChange={(v) => set('remarks', v)} rows={2} />
					</Field>
				</div>
			</div>
			<div className="formfoot">
				{err && <span className="ferr">{err}</span>}
				{doc.source === 'Manual' && (
					<button type="button" className="btn" disabled={busy} onClick={() => void onDelete()}>
						{deleting ? 'Removing…' : 'Remove'}
					</button>
				)}
				<span className="spacer" />
				{canGenerate && (
					<button type="button" className="btn" disabled={busy} onClick={() => void onGenerate()}>
						<Icon name="file-text" size={14} /> {generating ? 'Generating…' : fileUrl ? 'Regenerate PDF' : 'Generate PDF'}
					</button>
				)}
				<button type="button" className="btn" onClick={onClose}>
					Cancel
				</button>
				<button type="button" className="btn primary" disabled={busy} onClick={() => void onSave()}>
					{saving ? 'Saving…' : 'Save'}
				</button>
			</div>
		</Modal>
	);
}

/** Manual checklist row (never auto-removed by the engine). */
function AddDocumentModal({
	shipment,
	types,
	onClose,
	onSaved,
}: {
	shipment: string;
	types: DocTypeOption[];
	onClose: () => void;
	onSaved: () => void;
}) {
	const [docType, setDocType] = useState('');
	const [remarks, setRemarks] = useState('');
	const [err, setErr] = useState<string | null>(null);
	const { call: add, loading } = useFrappePostCall(API.addDocInstance);

	async function onAdd() {
		if (!docType) return setErr('Pick a document type.');
		setErr(null);
		try {
			await add({ shipment, document_type: docType, remarks: remarks || null });
			onSaved();
		} catch (e) {
			setErr(parseServerError(e));
		}
	}

	return (
		<Modal title="Add document" icon="plus" onClose={onClose}>
			<div className="formgrid">
				<div className="span2">
					<Field label="Document type" required>
						<SearchSelect
							value={docType}
							onChange={setDocType}
							placeholder="Search document types…"
							options={types.map((t) => ({ value: t.name, sub: `${t.category} · ${t.origin}` }))}
						/>
					</Field>
				</div>
				<div className="span2">
					<Field label="Remarks">
						<TextArea value={remarks} onChange={setRemarks} rows={2} />
					</Field>
				</div>
			</div>
			<div className="formfoot">
				{err && <span className="ferr">{err}</span>}
				<span className="spacer" />
				<button type="button" className="btn" onClick={onClose}>
					Cancel
				</button>
				<button type="button" className="btn primary" disabled={loading} onClick={() => void onAdd()}>
					{loading ? 'Adding…' : 'Add to checklist'}
				</button>
			</div>
		</Modal>
	);
}
