"""Spec §5.1 Document Type catalog and §5.3 standard checklist rules.

Seeded idempotently from after_install and from a patch (existing records are
never touched — the client may rename/retune them). The rule set mirrors the
spec's base + conditional lists; destination-country rules are left to the
client to add per customer market (Settings → Checklist rules).
"""

# (name, category, origin, responsible, attaches_to, extras)
DOCUMENT_TYPES = [
	# Commercial — generated by ExportFlow (Us)
	("Pro Forma Invoice", "Commercial", "Generated", "Us", "Sales Order",
	 {"default_print_format": "Pro Forma Invoice"}),
	("Commercial Invoice", "Commercial", "Generated", "Us", "Shipment",
	 {"default_print_format": "ExportFlow Commercial Invoice"}),
	("Packing List", "Commercial", "Generated", "Us", "Shipment",
	 {"default_print_format": "ExportFlow Packing List"}),
	("Delivery Instruction to Supplier", "Commercial", "Generated", "Us", "Purchase Order",
	 {"notes": "Generated from the purchase-order screen (format arrives with the PO documents phase)"}),
	("Shipping Instruction to CHA", "Commercial", "Generated", "Us", "Shipment",
	 {"default_print_format": "ExportFlow Shipping Instruction"}),
	("SCOMET Non-Applicability Declaration", "Commercial", "Generated", "Us", "Shipment",
	 {"default_print_format": "ExportFlow SCOMET Declaration"}),
	("Bill of Exchange", "Commercial", "Generated", "Us", "Shipment",
	 {"default_print_format": "ExportFlow Bill of Exchange"}),
	("Bank Presentation Covering Schedule", "Commercial", "Generated", "Us", "Shipment",
	 {"default_print_format": "ExportFlow Covering Schedule"}),
	# Regulatory — tracked
	("Shipping Bill", "Regulatory", "Tracked", "CHA", "Shipment",
	 {"is_blocking": 1, "blocked_milestone": "Let Export Order", "min_unblock_status": "Sent/Filed"}),
	("Let Export Order", "Regulatory", "Tracked", "Authority", "Shipment", {}),
	("EGM", "Regulatory", "Tracked", "Authority", "Shipment", {}),
	("ADC NOC", "Regulatory", "Tracked", "CHA", "Shipment",
	 {"is_blocking": 1, "blocked_milestone": "Let Export Order", "min_unblock_status": "Received"}),
	("State Drug Controller Export NOC", "Regulatory", "Tracked", "Authority", "Shipment", {}),
	("GST Supplier Compliance Pack", "Regulatory", "Tracked", "Us", "Purchase Order",
	 {"notes": "Shipping bill copy + EGM proof to the supplier and their jurisdictional officer (§4.3)"}),
	# Quality — tracked, from supplier
	("Certificate of Analysis", "Quality", "Tracked", "Supplier", "Shipment", {}),
	("MSDS", "Quality", "Tracked", "Supplier", "Shipment", {}),
	("GMP Certificate of Manufacturer", "Quality", "Tracked", "Supplier", "Shipment", {"has_expiry": 1}),
	("COPP", "Quality", "Tracked", "Supplier", "Shipment", {"has_expiry": 1}),
	("Free Sale Certificate", "Quality", "Tracked", "Authority", "Shipment", {}),
	("Batch Manufacturing Record", "Quality", "Tracked", "Supplier", "Shipment", {}),
	("TSE/BSE Declaration", "Quality", "Tracked", "Supplier", "Shipment", {}),
	("Nitrosamine Declaration", "Quality", "Tracked", "Supplier", "Shipment", {}),
	# Logistics — tracked
	("Booking Confirmation", "Logistics", "Tracked", "Shipping Line/Airline", "Shipment", {}),
	("VGM Declaration", "Logistics", "Tracked", "CHA", "Shipment", {}),
	("Bill of Lading", "Logistics", "Tracked", "Shipping Line/Airline", "Shipment", {}),
	("Air Waybill", "Logistics", "Tracked", "Shipping Line/Airline", "Shipment", {}),
	("Marine/Transit Insurance Certificate", "Logistics", "Tracked", "Us", "Shipment", {}),
	("Certificate of Origin", "Logistics", "Tracked", "Us", "Shipment",
	 {"notes": "DGFT eCoO / chamber of commerce"}),
	("Freight Invoice", "Logistics", "Tracked", "Shipping Line/Airline", "Shipment", {}),
	# Banking — tracked
	("LC Copy & Amendments", "Banking", "Tracked", "Bank", "Sales Order", {}),
	("eBRC", "Banking", "Tracked", "Bank", "Shipment", {}),
	("FIRC", "Banking", "Tracked", "Bank", "Shipment", {}),
	("Document Courier AWB", "Banking", "Tracked", "Us", "Shipment", {}),
	# Company — compliance register types (Compliance Record arrives Phase 5)
	("IEC", "Company", "Tracked", "Us", "Company", {}),
	("GST Registration", "Company", "Tracked", "Us", "Company", {}),
	("LUT", "Company", "Tracked", "Us", "Company", {"has_expiry": 1}),
	("RCMC Pharmexcil", "Company", "Tracked", "Us", "Company", {"has_expiry": 1}),
	("Wholesale Drug License", "Company", "Tracked", "Us", "Company", {"has_expiry": 1}),
	("AD Code", "Company", "Tracked", "Us", "Company", {"notes": "Registered per port — see Port master"}),
	("Bank Details", "Company", "Tracked", "Us", "Company", {}),
]

# (rule_name, document_type, [(condition_field, condition_value), ...])
# No conditions = base set (§5.3, always required on every shipment).
CHECKLIST_RULES = [
	("Base: Commercial Invoice", "Commercial Invoice", []),
	("Base: Packing List", "Packing List", []),
	("Base: Shipping Instruction to CHA", "Shipping Instruction to CHA", []),
	("Base: SCOMET Declaration", "SCOMET Non-Applicability Declaration", []),
	("Base: Shipping Bill", "Shipping Bill", []),
	("Base: ADC NOC", "ADC NOC", []),
	("Base: Let Export Order", "Let Export Order", []),
	("Base: EGM", "EGM", []),
	("Base: Certificate of Analysis", "Certificate of Analysis", []),
	("Base: Booking Confirmation", "Booking Confirmation", []),
	("Base: Certificate of Origin", "Certificate of Origin", []),
	("Sea: Bill of Lading", "Bill of Lading", [("mode", "Sea")]),
	("Sea: VGM Declaration", "VGM Declaration", [("mode", "Sea")]),
	("Air: Air Waybill", "Air Waybill", [("mode", "Air")]),
	("CIF/CIP: Insurance Certificate", "Marine/Transit Insurance Certificate", [("incoterm", "CIF, CIP")]),
	("LC: Bill of Exchange", "Bill of Exchange", [("letter_of_credit", "Yes")]),
	("LC: Covering Schedule", "Bank Presentation Covering Schedule", [("letter_of_credit", "Yes")]),
	("LC: Document Courier AWB", "Document Courier AWB", [("letter_of_credit", "Yes")]),
	("LC: eBRC follow-up", "eBRC", [("letter_of_credit", "Yes")]),
]
